config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'tree/index'
  get 'description/index'

  get 'dashboard/index'

  get 'basic_statistics/index'
  get 'basic_statistics_frequency/index'

  resources :attestations, only: %i[index show]
  resources :coptic_sublemmas, only: %i[index show]
  resources :greek_lemmas, only: %i[index show]
  resources :morpho_syntaxes, only: %i[index show]
  resources :orthographies, only: %i[index show]
  resources :sources, only: %i[index show]


  root 'dashboard#index'

end

app/models/source.rb
class Source < ApplicationRecord
  has_many :attestations
  has_many :morpho_syntaxes, through: :attestations
  has_many :orthographies, through: :attestations

  def typologies
    [typo_broad, typo_content, typo_form,
     typo_sociohistoric, typo_speccorpus, typo_subjectmatter].compact
  end

  def dating_interval
    [dating_start, dating_end].compact
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  def index
    @sources =
      if params[:ids].nil?
        Source.all.page(params[:page])
      else
        Source.where("id in (#{params[:ids][1...-1]})").page(params[:page])
      end
  end

  def show
    @source = Source.find(params[:id])
  end
end

app/views/sources/index.html.haml
%section
  - @sources.each do |source|
    = "#{source.manuscript}, #{source.text}:"
    %ul
      %li
        Dating:
        - if source.dating_interval.empty?
          unknown
        - else
          = source.dating_interval.join(' to ')
      %li= "Dialect: #{source.dialect}"
      %li= link_to 'more information', source_path(source.id)
  =paginate @sources
  =page_entries_info @sources

app/views/sources/show.html.haml
%section
  %ul
    %li= "Manuscript: #{@source.manuscript}"
    %li= "Text: #{@source.text}"
    %li
      Dating:
      - if @source.dating_interval.empty?
        unknown
      - else
        = @source.dating_interval.join(' to ')
    %li= "Dialect: #{@source.dialect}"
    %li= "Typology: #{@source.typologies.join(', ')}"