config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'tree/index'
  get 'description/index'

  get 'dashboard/index'

  get 'basic_statistics/index'
  get 'basic_statistics_frequency/index'

  resources :attestations, only: %i[index show]
  resources :coptic_sublemmas, only: %i[index show]
  resources :greek_lemmas, only: %i[index show]
  resources :morpho_syntaxes, only: %i[index show]
  resources :orthographies, only: %i[index show]
  resources :sources, only: %i[index show]


  root 'dashboard#index'

end

app/views/shared/_abstraction.html.haml
.panel-group#accordionInnerAbstraction{:role=>"tablist", 'aria-multiselectable'=>"true"}
  .panel.panel-default
    .panel-heading#dataAbstraction{:role=>"tab"}
      %h4.panel-title
        %a{:role=>"button", 'data-toggle'=>"collapse", 'data-parent'=>"#accordionInnerAbstraction", :href=>"#collapseOneInner", 'aria-expanded'=>"true", 'aria-controls'=>"collapseOneInner"}
          Data abstraction
    .panel-collapse.collapse#collapseOneInner{:role=>"tabpanel", 'aria-labelledby'=>"dataAbstraction"}
      .panel-body
        .row
          .col-xs-7.col-md-offset-1
            %table.table.table-hover
              %thead
                %tr
                  %th
                    Criterion
                  %th
                    Value
                %tbody
                  %tr
                    %td
                      %i stored dataset type
                    %td relational/ table
                  %tr
                    %td
                      %i logical dataset type
                    %td network/ tree
                  %tr
                    %td
                      %i dataset availability
                    %td static
                  %tr
                    %td
                      %i items and attributes
                    %td
                      %ul.list-in-table.fa-ul
                        %li
                          %i.fa-li.fa.fa-check-square-o
                          %b Greek lemma:
                          %br
                          label, meaning, part-of-speech
                        %li
                          %i.fa-li.fa.fa-check-square-o
                          %b Coptic sublemma:
                          %br
                          label, part-of-speech
                        %li
                          %i.fa-li.fa.fa-check-square-o
                          %b Orthography:
                          %br
                          label
                        %li
                          %i.fa-li.fa.fa-check-square-o
                          %b Morpho-Syntax:
                          %br
                          label
                        %li
                          %i.fa-li.fa.fa-check-square-o
                          %b Source:
                          %br
                          dating interval, dialect (rough localisation), manuscript, text,
                          %br
                          set of typology categories
                  %tr
                    %td
                      %i links and attributes
                    %td
                      %table#link-table
                        %tbody
                          %tr
                            %td Coptic sublemma
                            %td
                              %i derives from
                            %td Greek lemma
                          %tr
                            %td Orthography
                            %td
                              %i is a variant of
                            %td Coptic sublemma
                          %tr
                            %td Orthography
                            %td
                              %i is attested in
                            %td Source
                            %td
                              %i w.r.t.
                            %td Morpho-Syntax
          .col-xs-4
            = image_tag('datamodel.svg', class: 'img-responsive')
  .panel.panel-default
    .panel-heading#taskAbstraction{:role=>"tab"}
      %h4.panel-title
        %a{:role=>"button", 'data-toggle'=>"collapse", 'data-parent'=>"#accordionInnerAbstraction", :href=>"#collapseTwoInner", 'aria-expanded'=>"true", 'aria-controls'=>"collapseTwoInner"}
          Task abstraction
    .panel-collapse.collapse#collapseTwoInner{:role=>"tabpanel", 'aria-labelledby'=>"taskAbstraction"}
      .panel-body
        .row
          .col-xs-10.col-md-offset-1
            %table.table.table-hover#task-table
              %thead
                %tr
                  %th Task
                  %th Target
                  %th Example
                  %th Comment
                %tbody
                  %tr
                    %td Analyze ➟ Consume ➟ Discover
                    %td All Data ➟ Trends
                    %td
                      = link_to image_tag('overview1.png', class: 'thumbnail'), basic_statistics_index_path, target: '_blank'
                    %td —
                  %tr
                    %td Analyze ➟ Produce ➟ Derive
                    %td All Data ➟ Trends
                    %td
                      = link_to image_tag('overview1.png', class: 'thumbnail'), basic_statistics_index_path, target: '_blank'
                    %td
                      derived: orthography frequencies
                  %tr
                    %td Query ➟ Compare
                    %td Attributes ➟ One
                    %td
                      = link_to image_tag('frequency.png', class: 'thumbnail'), basic_statistics_frequency_index_path, target: '_blank'
                    %td —
                  %tr
                    %td Search ➟ Lookup
                    %td Attributes ➟ One
                    %td
                      = link_to image_tag('tree.png', class: 'thumbnail'), tree_index_path, target: '_blank'
                    %td select root of the tree
                  %tr
                    %td Search ➟ Browse
                    %td Network Data ➟ Paths
                    %td
                      = link_to image_tag('tree.png', class: 'thumbnail'), tree_index_path, target: '_blank'
                    %td —

app/views/shared/_algorithms.html.haml
.row
  .xs-9.col-md-offset-1
    %ul.list-in-table
      %li
        Database
        %br
        relational (second normal form):
        = link_to image_tag('includes-mysql-88x31.png', class: 'thumbnail'), 'https://www.mysql.com', target: '_blank'
      %li
        Framework
        %table
          %tbody
            %tr
              %td
                Ruby on Rails
                = link_to image_tag('rails-logo.svg', class: 'thumbnail alg'), 'http://rubyonrails.org/', target: '_blank'
              %td
                Bootstrap
                = link_to image_tag('144px-Boostrap_logo.svg.png', class: 'thumbnail alg'), 'https://getbootstrap.com/', target: '_blank'
            %tr
              %td
                Highcharts
                = link_to image_tag('highcharts_logo.svg', class: 'thumbnail alg'), 'https://www.highcharts.com/', target: '_blank'
              %td
                D3
                = link_to image_tag('d3_logo.svg', class: 'thumbnail alg'), 'https://d3js.org/', target: '_blank'

app/views/shared/_domain_situation.html.haml
.row
  .col-xs-7.col-md-offset-1
    %table.table.table-hover
      %thead
        %tr
          %th
            Criterion
          %th
            Value
        %tbody
          %tr
            %td
              %i domain
            %td Coptology, linguistics
          %tr
            %td
              %i topic
            %td Greek loanwords, particularly their orthographies
          %tr
            %td
              %i source
            %td
              = link_to 'DDGLC project', 'http://www.research.uni-leipzig.de/ddglc'
          %tr
            %td
              %i data
            %td categorization of orthographies based on the underlying Greek lemma, Coptic sublemma, as well as manuscript and text information
          %tr
            %td
              %i aims
            %td
              %ul.list-in-table.fa-ul
                %li
                  %i.fa-li.fa.fa-check-square-o
                  gain a clear view of orthographies
                %li
                  %i.fa-li.fa.fa-check-square-o
                  change of orthographies over time
  .col-xs-4
    = link_to image_tag('coptic.jpg', class: 'img-responsive'), 'https://commons.wikimedia.org/wiki/File:Coptic_Manuscript_MET_sf19-196-4a.jpg', target: '_blank'

app/views/shared/_idioms.html.haml
.panel-group#accordionInnerIdioms{:role=>"tablist", 'aria-multiselectable'=>"true"}
  .panel.panel-default
    .panel-heading#idiomEncoding{:role=>"tab"}
      %h4.panel-title
        %a{:role=>"button", 'data-toggle'=>"collapse", 'data-parent'=>"#accordionInnerIdioms", :href=>"#collapseOneInnerIdiom", 'aria-expanded'=>"true", 'aria-controls'=>"collapseOneInnerIdiom"}
          Visual Encoding
    .panel-collapse.collapse#collapseOneInnerIdiom{:role=>"tabpanel", 'aria-labelledby'=>"idiomEncoding"}
      .panel-body
        .row
          .col-xs-9.col-md-offset-1
            %table.table.table-hover
              %thead
                %tr
                  %th Visualization
                  %th Mark
                  %th Channel
                  %th Meaning
                %tbody
                  %tr
                    %td Tree
                    %td Point
                    %td
                      %ul.list-in-table
                        %li
                          Color hue
                          %span.noun-color ■
                          %span.verb-color ■
                          %span.adjective-color ■
                          %span.adverb-color ■
                          %span.default-color ■
                        %li
                          Shape 🞎 🞔
                        %li vertical position ↓
                    %td
                      %ul.list-in-table
                        %li part-of-speech
                        %li node has hidden children
                        %li ranking due to latest attested orthography
                  %tr
                    %td Tree
                    %td Link marks
                    %td
                      %ul.list-in-table
                        %li horizontal position ⟶
                    %td
                      %ul.list-in-table
                        %li
                          %i derives from, is a variant of, is attested in
                  %tr
                    %td Tree
                    %td Line
                    %td
                      %ul.list-in-table
                        %li
                          Color hue
                          %span.a-dialect-color ■
                          %span.l-dialect-color ■
                          %span.s-dialect-color ■
                          %span.m-dialect-color ■
                          %span.b-dialect-color ■
                          %span.default-color ■
                        %li length – ⸺ ⸻
                        %li vertical position ↓
                    %td
                      %ul.list-in-table
                        %li dialect
                        %li frequency
                        %li approximate attestation date of orthography


  .panel.panel-default
    .panel-heading#idiomInteraction{:role=>"tab"}
      %h4.panel-title
        %a{:role=>"button", 'data-toggle'=>"collapse", 'data-parent'=>"#accordionInnerIdioms", :href=>"#collapseTwoInnerIdiom", 'aria-expanded'=>"true", 'aria-controls'=>"collapseTwoInnerIdiom"}
          Interaction
    .panel-collapse.collapse#collapseTwoInnerIdiom{:role=>"tabpanel", 'aria-labelledby'=>"idiomInteraction"}
      .panel-body
        .row
          .col-xs-8.col-md-offset-1
            %table.table.table-hover#task-table
              %thead
                %tr
                  %th Interaction
                  %th Where
                  %th Result
                %tbody
                  %tr
                    %td Manipulate ➟ Select
                    %td Tree, each node
                    %td redirected to data view
                  %tr
                    %td Manipulate ➟ Navigate
                    %td Tree, each parent node
                    %td toggle visibility of children
                  %tr
                    %td Reduce ➟ Filter
                    %td Tree, initial selection
                    %td created tree only for selected Greek lemma

app/views/shared/_navigation.html.haml
= navbar container: 'fluid' do
  = navbar_header brand: 'Loanword Orthographies'
  = navbar_collapse do
    = navbar_group id: 'menu' do
      = navbar_item 'Home', root_path
      = navbar_dropdown 'Basic Statistics' do
        = navbar_dropdown_header 'Choose an Overview Chart'
        = navbar_item 'Time-Dependent Overview', basic_statistics_index_path
        = navbar_item 'Frequency Distribution', basic_statistics_frequency_index_path
      = navbar_item 'Tree', tree_index_path
      = navbar_dropdown 'Data' do
        = navbar_dropdown_header 'Choose your data'
        = navbar_item 'Greek Lemmas', greek_lemmas_path
        = navbar_item 'Coptic Sublemmas', coptic_sublemmas_path
        = navbar_item 'Orthographies', orthographies_path
        = navbar_item 'Attestations', attestations_path
        = navbar_item 'Sources', sources_path
        = navbar_dropdown_divider
        = navbar_item 'Manage the data', '/admin'
      = navbar_item 'Project Description', description_index_path
      = navbar_item 'Crum dictionary', 'http://coptot.manuscriptroom.com/crum-coptic-dictionary', target: '_blank'
    = navbar_group align: 'right', id: 'ddglc_reference' do
      = link_to 'http://research.uni-leipzig.de/ddglc/', target: :_blank do
        = image_tag('ddglc_logo.jpg', class: :ddglc_logo, height: '50', alt: 'DDGLC', id: 'ddglc_logo')

app/views/shared/_random_phrase.html.haml
- parts = GreekLemma.random_determinator_phrase
= parts[:det]
= link_to parts[:adj], greek_lemma_path(parts[:adj_id])
= link_to parts[:noun], greek_lemma_path(parts[:noun_id])