config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'tree/index'
  get 'description/index'

  get 'dashboard/index'

  get 'basic_statistics/index'
  get 'basic_statistics_frequency/index'

  resources :attestations, only: %i[index show]
  resources :coptic_sublemmas, only: %i[index show]
  resources :greek_lemmas, only: %i[index show]
  resources :morpho_syntaxes, only: %i[index show]
  resources :orthographies, only: %i[index show]
  resources :sources, only: %i[index show]


  root 'dashboard#index'

end

app/models/orthography.rb
class Orthography < ApplicationRecord
  belongs_to :coptic_sublemma
  has_many :attestations
  has_many :morpho_syntaxes, through: :attestations
  has_many :sources, through: :attestations

  paginates_per 15
end

app/controllers/orthographies_controller.rb
class OrthographiesController < ApplicationController
  def index
    @orthographies = Orthography.all.order(:coptic_sublemma_id).page(params[:page])
  end

  def show
    @orthography = Orthography.find(params[:id])
  end
end

app/views/orthographies/index.html.haml
%section
  - @orthographies.each do |orthography|
    %b= link_to("#{orthography.label}", orthography_path(orthography.id))
    %p
      orthography of
      = link_to orthography.coptic_sublemma.label, coptic_sublemma_path(orthography.coptic_sublemma_id)
  =paginate @orthographies
  =page_entries_info @orthographies

app/views/orthographies/show.html.haml
%body
  .orthography
    .orthography-label
      %b= @orthography.label
    .reference
      = link_to "Go to Coptic sublemma", coptic_sublemma_path(@orthography.coptic_sublemma_id)
    .reference
      = link_to "Go to Sources", "http://localhost:3000/sources?ids=#{@orthography.sources.pluck(:id)}"
  = link_to 'Orthographies', orthographies_path